---
title: "Joshua French"
date: "`r format(Sys.time(), '%Y-%m-%d')`"
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
---

# Linear model inference

With our regression model, we also hope to be able to:

  1. *Generalize* our results from the sample to the a larger population of interest.
* E.g., we want to extend our results from a small set of college students to all college students.
2. *Infer causality* between our regressors and the response.
* E.g., if a person receives the measles vaccine, then this causes a reduction in the person's risk of catching measles.

Results from a sample of observations typically only generalize to a larger population when the sample is a random sample from a larger population. Some examples of random sampling methods include simple random sampling, stratified random sampling, cluster random sampling, and systematic random sampling. Most inferential methods assume the $n$ observations are a simple random sample from a larger population. Simple random sampling requires that each sample of size $n$ is equally likely to occur.

Causal inference can be made when the data are a
