--- 
title: "Data Analysis with Linear Regression"
author: "Joshua French"
date: "`r format(Sys.time(), '%Y-%m-%d')`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: "A collection of R notebooks demonstrating how to perform data analysis   with linear regression."
---

# Preliminaries

I recommend you execute the following commands install packages we may use in this course.

```{r, eval = FALSE}
# packages related to books
books = c("faraway", "alr4", "car", "rms")
install.packages(books)
# packages related to tidy/tidying data
tidy = c("broom", "tidyr", "dplyr")
install.packages(tidy)
# packages related to plotting
moreplots = c("ggplot2", "ggthemes", "lattice", "HH")
install.packages(moreplots)
# packages related to model diagnostics
diag = c("leaps", "lmtest", "gvlma", "caret", "perturb")
install.packages(diag)
```

*Acknowledgments*

The **bookdown** package [@R-bookdown] was used to generate this book.

```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```
