#options(width = 45) #nice Word formatting at 20pts
options(digits = 5, scipen = 2, show.signif.stars = FALSE)

library(car)

# load data
data(Prestige, package = "carData")

# fit model
lmod = lm(prestige ~ education + income + type,
          data = Prestige)

# examine residual plots
residualPlots(lmod)

# mimic lof test for income
lmod.lofi = lm(prestige ~ education + income +
                 I(income^2) + type, data = Prestige)
# test statistic and p-value for I(income^2) are
# -2.89 and 0.0049, as expected
summary(lmod.lofi)

# mimic tukey's test
yhatall = predict(lmod, newdata = Prestige)
lmod.tukeytest = lm(prestige ~ education + income +
                    type + I(yhatall^2), data = Prestige)
summary(lmod.tukeytest)

# examine marginal model plot
marginalModelPlots(lmod)

# examine added variable plots
avPlots(lmod, col.lines = NULL, id = FALSE)

# fit slightly different model
lmod = lm(prestige ~ education + income + women, data = Prestige)

# av plot for education alone
avPlot(lmod, "education")

# recreating the av plot for education manually
# regressing the response on all other regressors
deltahat = residuals(lm(prestige ~ income + women, data = Prestige))
# regressoing education on all other regressors
gammahat = residuals(lm(education ~ income + women, data = Prestige))
# plotting deltahat vs gammahat
plot(deltahat ~ gammahat)
# adding a loess smoother to the added variable plot
# fit a loess smooth
loess_fit <- loess(deltahat ~ gammahat)
# create a sequence of x-values to make predictions
x_values <- seq(min(gammahat), max(gammahat), len = 100)
# predict the response for the sequence of x-values
y_values <- predict(loess_fit, newdata = data.frame(gammahat = x_values))
# connect the points together
lines(x_values, y_values, col = "blue")

# do something similar for the income variable
avPlot(lmod, "income")
deltahat = residuals(lm(prestige ~ education + women, data = Prestige))
gammahat = residuals(lm(income ~ education + women, data = Prestige))
plot(deltahat ~ gammahat)
loess_fit <- loess(deltahat ~ gammahat)
x_values <- seq(min(gammahat), max(gammahat), len = 100)
y_values <- predict(loess_fit, newdata = data.frame(gammahat = x_values))
lines(x_values, y_values, col = "blue")

# examine component plus residual plots
crPlots(lmod)

lmod2 = lm(prestige ~ education + sqrt(income) + women, data = Prestige)
crPlots(lmod2)

lmod3 = lm(prestige ~ education + log(income) + women, data = Prestige)
crPlots(lmod3)

lmod4 = lm(prestige ~ education + log(income) +
             poly(women, 2), data = Prestige)
crPlots(lmod4)

# examine ceres plots
ceresPlots(lmod)

## Appendix

# generate random x-values
x = rnorm(50)
# generate polynomials of degree 5
xp = sapply(1:5, function(p) x^p)
# highly correlated
round(cor(xp), 3)
# center each polynomial
xpc = scale(xp, scale = FALSE)
# find the Q matrix of the QR decomposition
# of xpc
xpoly = qr.Q(qr(xpc))
# correlation between xpoly and the values
# generated by the poly function
round(cor(xpoly, poly(x, 5)), 3)

# the logistic function
x = seq(0.01, 0.99, len = 100)
plot(x, logit(x), type = "l", xlab = "probability")
